{{- $name := "ckan" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-config" (include "common.names.fullname" $) $name | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
stringData:
  sysAdminUsername: {{ .Values.ckan.sysadmin.name | quote }}
  sysAdminPassword: {{ .Values.ckan.sysadmin.password | quote }}
  sysAdminEmail: {{ .Values.ckan.sysadmin.email | quote }}
  smtpPassword: {{ .Values.ckan.smtp.password | quote }}
  postgresUsername: {{ .Values.postgresql.auth.postgresPassword | quote}}
  ckanDatabaseUsername: {{ .Values.postgresql.auth.username | quote }}
  ckanDatabasePassword: {{ .Values.postgresql.auth.password | quote }}
  datastoreUsername: {{ .Values.postgresql.ckanDbs.datastoreUsername | quote}}
  datastorePassword: {{ .Values.postgresql.ckanDbs.datastorePassword | quote}}
  datapusherUsername: {{ .Values.postgresql.ckanDbs.datapusherUsername | quote}}
  datapusherPassword: {{ .Values.postgresql.ckanDbs.datapusherPassword | quote}}